apiVersion: apps/v1
kind: Deployment
metadata:
  name: Game
  labels:
    app: Game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Game
  template:
    metadata:
      labels:
        app: Game
    spec:
      containers:
        - name: Game
          image: username/Game:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5