---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Game
  labels:
    app: Game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Game
  template:
    metadata:
      labels:
        app: Game
    spec:
      containers:
        - name: Game
          image: username/Game:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: View
  labels:
    app: View
spec:
  replicas: 1
  selector:
    matchLabels:
      app: View
  template:
    metadata:
      labels:
        app: View
    spec:
      containers:
        - name: View
          image: username/View:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Purchase
  labels:
    app: Purchase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Purchase
  template:
    metadata:
      labels:
        app: Purchase
    spec:
      containers:
        - name: Purchase
          image: username/Purchase:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Payment
  labels:
    app: Payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Payment
  template:
    metadata:
      labels:
        app: Payment
    spec:
      containers:
        - name: Payment
          image: username/Payment:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Message
  labels:
    app: Message
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Message
  template:
    metadata:
      labels:
        app: Message
    spec:
      containers:
        - name: Message
          image: username/Message:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: Game
  labels:
    app: Game
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Game


---


apiVersion: v1
kind: Service
metadata:
  name: View
  labels:
    app: View
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: View


---


apiVersion: v1
kind: Service
metadata:
  name: Purchase
  labels:
    app: Purchase
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Purchase


---


apiVersion: v1
kind: Service
metadata:
  name: Payment
  labels:
    app: Payment
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Payment


---


apiVersion: v1
kind: Service
metadata:
  name: Message
  labels:
    app: Message
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Message

